name: scripts
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

#Old
# dependencies:
#   dart_appwrite: ^0.4.0
# #   path: ^1.8.0
# dev_dependencies:
#   pedantic: ^1.10.0

# New
dependencies:
  flutter:
    sdk: flutter
  appwrite: ^0.5.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_appwrite: ^0.5.0-dev.1

flutter:
  uses-material-design: true