name: scripts
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_appwrite: ^0.6.3

dev_dependencies:
  pedantic: ^1.11.0
